language: go
cache:
  directories:
  - vendor
  - $GOPATH/src
go:
  - 1.8
install:
  - make bootstrap
script:
  - make ci
before_deploy:
  - make VERSION=${TRAVIS_TAG} buildrelease
deploy:
  provider: releases
  api_key:
    secure: h/mjTM1ZDG7oEGk61uMiVtVPbDvoup0FFOrUVIy8oRbtw2aZLnYsJpWNbbT5ahl73GCYqazK3qWQjLvE8j7w6FkwlJLxotVm7X68voMQMLCIz6hN6LmvyhfH14XRnGVg+hvlYtFfUWurQXmhix6XoMa5V2lIQ/iONFvKX1zw9MWH+nIZi+1HrSNiHdglbroD5B1FDWx6qSVv70H4dUIatQxoU+68LOmqzkZpdW1wQbssObU45iE3uqST02G8UebS/dmHXVTkipcDo/CWa5kFv2CLAM9P3reZbqwvMbjhGxm3kuYgz4qwDaBvroy6qweTKGnLma3a2+ZS30JmdQUHsbnDe9Q0Kb6xZIZjl0OH2/zI6hEKeNAqlK5H7YFTJLWqSTGr0sD+4IRACFGwi8bWaY799GC5T7rPz7KKgvuX1xnaqRxFoNV68AZU7sgO2faikHm3EGYmLHr5ZmqHvNnrEokbIXvTmUI64jEMcSKRebyoWK99sXTuhXWuKVoMWz8tKIP5wJVo7p/KsfpIId5QJxLXphb7s44lAUrtTP7KNWyrqbX2Hxi6Ud3PqQlMIhhweB2fJAuMlFkJVMqDkOeVs3Po3uyQvx9iEZVdAVMX052vlB5uNfywC+CjLJuapxXu8mz4bSiTBuVARYYxu1kPBRmb7GBGFfoAXcrUDUWLeXs=
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
