[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  version = "v0.0.2"
  name = "github.com/mattn/go-isatty"

